import { useState, useEffect, useContext } from "react";
import { AppContext } from '../../context/AppContext'
import api from "../../services/axiosInstance";
import { Loader2, Sparkles, SquarePen } from "lucide-react";

const TitleSelection = () => {
  const { storyId } = useContext(AppContext);
  const [storyData, setStoryData] = useState(null);

  const [aiTitles, setAiTitles] = useState([]); // MUST be array
  const [selectedTitle, setSelectedTitle] = useState("");

  const [loadingTitles, setLoadingTitles] = useState(false);
  const [creatingBook, setCreatingBook] = useState(false);

  useEffect(() => {
    fetchStoryData();
  }, []);

  const fetchStoryData = async () => {
    try {
      const res = await api.get(`/api/v1/story/${storyId}`);
      const story = res.data.data.story;
      setStoryData(story);
      setSelectedTitle(story.title || "");
    } catch (err) {
      console.error("Fetch story failed:", err);
    }
  };

  const handleGenerateTitles = async () => {
    try {
      setLoadingTitles(true);
      setAiTitles([]);

      const res = await api.post("/api/v1/story/titles/generate", {
        storyId,
        story: storyData?.gist, 
        genre: storyData?.genre
      });

      // Titles must be an array! 
      setAiTitles(res.data.titles || []);
    } catch (err) {
      console.error("AI Title fetch failed:", err);
    } finally {
      setLoadingTitles(false);
    }
  };

  const handleCreateBook = async () => {
    try {
      setCreatingBook(true);

      // YOU WILL ADD API CALL HERE
      console.log("Final Title Submitted:", selectedTitle);

    } catch (err) {
      console.error(err);
    } finally {
      setCreatingBook(false);
    }
  };

  return (
    <div className="p-6 py-10 max-w-3xl mx-auto text-white">

      {/* MAIN HEADING */}
      <h1 className="text-3xl font-bold text-purple-400 mb-4">
        Choose Your Book Title
      </h1>

      {/* CURRENT TITLE */}
      <p className="text-gray-300 mb-2">
        You can use your own title or choose one generated by AI.
      </p>

      <div className="bg-gray-800 p-4 rounded-lg border border-gray-700 mb-6">
        <h2 className="text-xl font-semibold text-purple-300 mb-2">
          Current Title
        </h2>
        <p className="text-lg">{storyData?.title || "—"}</p>
      </div>

      {/* Generate AI Titles Button */}
      <button
        className="w-full bg-purple-600 hover:bg-purple-700 py-3 rounded-lg font-semibold flex items-center justify-center gap-2"
        onClick={handleGenerateTitles}
        disabled={loadingTitles}
      >
        {loadingTitles ? (
          <>
            <Loader2 className="animate-spin" />
            Generating AI Titles...
          </>
        ) : (
          <>
            <Sparkles size={20} />
            Generate Better Titles
          </>
        )}
      </button>

      {/* Loader Animation (not overlay) */}
      {loadingTitles && (
        <div className="mt-6 text-center">
          <div className="py-6 animate-pulse text-purple-300">
            <p className="text-lg">✨Crafting Better Titles...<SquarePen className="inline"/></p>
          </div>
        </div>
      )}

      {/* AI GENERATED TITLES */}
      {aiTitles.length > 0 && (
        <div className="mt-6">
          <h2 className="text-xl font-bold text-purple-300 mb-3">
            AI Generated Titles
          </h2>

          <div className="flex flex-col gap-3">
            {aiTitles.map((t, index) => (
              <div
                key={index}
                onClick={() => setSelectedTitle(t)}
                className={`p-3 rounded-lg cursor-pointer border
                ${selectedTitle === t ? "border-purple-500 bg-gray-700" : "border-gray-700 bg-gray-800"}`}
              >
                {t}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* CUSTOM TITLE INPUT */}
      <div className="mt-8">
        <label className="block text-purple-300 mb-2 font-semibold">
          Enter Title you Liked 
        </label>
        <input
          className="w-full p-3 rounded-lg bg-gray-900 border border-gray-700 text-white"
          value={selectedTitle}
          onChange={(e) => setSelectedTitle(e.target.value)}
          placeholder="Write your book title..."
        />
      </div>

      {/* Final Submit Button */}
      <button
        className="w-full mt-6 bg-green-600 hover:bg-green-700 py-3 rounded-lg font-semibold"
        onClick={handleCreateBook}
        disabled={creatingBook}
      >
        {creatingBook ? (
          <div className="flex flex-col items-center py-2">
            <Loader2 className="animate-spin mb-2" />

            <p className="text-sm">
              Crafting your full magical book... ✨ this may take up to 10 minutes, take a coffee break while we work.
            </p>
          </div>
        ) : (
          "Create My Book"
        )}
      </button>

    </div>
  );
};

export default TitleSelection;
