import { useState, useEffect, useContext } from "react";
import { AppContext } from '../../context/AppContext'
import api from "../../services/axiosInstance";
import { useParams } from "react-router-dom";
import { Loader2, Sparkles, SquarePen } from "lucide-react";
import { ProgressStep4 } from '../helperComponents/Steps.jsx'

const TitleSelection = () => {
  const { navigateTo } = useContext(AppContext);
  const { storyId } = useParams();
  const [storyData, setStoryData] = useState(null);

  const [aiTitles, setAiTitles] = useState([]); // MUST be array
  const [selectedTitle, setSelectedTitle] = useState("");

  const [loadingTitles, setLoadingTitles] = useState(false);
  const [creatingBook, setCreatingBook] = useState(false);
  const [regenerate, setRegenerate] = useState(false);

  useEffect(() => {
    fetchStoryData();
    if (import.meta.env.DEV) console.log("Story ID:", storyId);
  }, []);

  const fetchStoryData = async () => {
    try {
      // const res = await api.get(`/api/v1/story/6939cb6e18374ba322e05efa`);
      const res = await api.get(`/api/v1/story/${storyId}`);
      const story = res.data.data.story;
      setStoryData(story);
      setSelectedTitle(story.title || "");
    } catch (err) {
      console.error("Fetch story failed:", err);
    }
  };

  // Generate AI Titles
  const handleGenerateTitles = async () => {
    if (import.meta.env.DEV) console.log("Generating titles for story ID:", storyId);
    try {
      setLoadingTitles(true);
      setAiTitles([]);

      const res = await api.post("/api/v1/story/titles/generate", {
        storyId,
        selectedTitle,
        // story: storyData?.gist,
        genres: storyData?.genres || (storyData?.genre ? [storyData.genre] : [])
      });

      // Titles must be an array! 
      // setAiTitles(res.data.titles || []);
      setAiTitles(res.data.data.titles || []);
      setRegenerate(true);
      
      // console.log("AI Titles Response:", res.data);
    } catch (err) {
      console.error("AI Title fetch failed:", err);
    } finally {
      setLoadingTitles(false);
    }
  };

  // For Regenerate Button
  const handleReGenerateTitles = async () => {
    try {
      setLoadingTitles(true);
      setAiTitles([]);

      const res = await api.post("/api/v1/story/titles/regenerate", {
        storyId,
        story: storyData?.gist,
        genres: storyData?.genres || (storyData?.genre ? [storyData.genre] : []),
        previousTitles: aiTitles,
        selectedTitle,
      });

      setAiTitles(res.data.data.titles || []);
      setRegenerate(true);
      
      // console.log("AI Titles Response:", res.data);
    } catch (err) {
      console.error("AI Title fetch failed:", err);
    } finally {
      setLoadingTitles(false);
    }
  };

  // Final Create Book Handler
  const handleCreateBook = async () => {
    try {
      setCreatingBook(true);

      // YOU WILL ADD API CALL HERE
      // console.log("Final Title Submitted:", selectedTitle);

      const res = await api.post(`/api/v1/images/generate-characters/${storyData._id}`, {
        title: selectedTitle,
      });

      if (import.meta.env.DEV) console.log("Book creation succeeded");
      navigateTo(`/backgroundgenerator/${res.data.storyId}`);

    } catch (err) {
      console.error(err);
    } finally {
      setCreatingBook(false);
    }
  };


  return (
     <div className="min-h-screen w-full bg-black text-white flex flex-col items-center px-6 py-10">
      <ProgressStep4 />
    <div className="p-6 py-10 relative max-w-3xl w-full text-white">
      {/* MAIN HEADING */}
      <h1 className="text-3xl font-bold text-purple-400 mb-4">
        Choose Your Book Title
      </h1>

      {/* CURRENT TITLE */}
      <p className="text-gray-300 mb-2">
        You can use your own title or choose one generated by AI.
      </p>

      <div className="bg-gray-800 p-4 rounded-lg border border-gray-700 mb-6">
        <h2 className="text-xl font-semibold text-purple-300 mb-2">
          Current Title
        </h2>
        <p className="text-lg">{storyData?.title || "—"}</p>
      </div>

      {/* Generate AI Titles Button */}
      {!regenerate ? ( 
            <button
              className="w-full bg-purple-600 hover:bg-purple-700 py-3 rounded-lg font-semibold flex items-center justify-center gap-2"
              onClick={handleGenerateTitles}
              disabled={loadingTitles}
            >
              {loadingTitles ? (
                <>
                  <Loader2 className="animate-spin" />
                  Generating AI Titles...
                </>
              ) : (
                <>
                  <Sparkles size={20} />
                  Generate Better Titles
                </>
              )}
            </button>
      ) : (
            <button
            className="w-full bg-purple-600 hover:bg-purple-700 py-3 rounded-lg font-semibold flex items-center justify-center gap-2"
            onClick={handleReGenerateTitles}
            disabled={loadingTitles}
          >
            {loadingTitles ? (
              <>
                <Loader2 className="animate-spin" />
                Regenerating AI Titles...
              </>
            ) : (
              <>
                <Sparkles size={20} />
                Regenerate Better Titles
              </>
            )}
          </button>
      )}

      {/* Loader Animation (not overlay) */}
      {loadingTitles && (
        <div className="mt-6 text-center">
          <div className="py-6 animate-pulse text-purple-300">
            <p className="text-lg">✨Crafting Better Titles...<SquarePen className="inline"/></p>
          </div>
        </div>
      )}

      {/* AI GENERATED TITLES */}
      {aiTitles.length > 0 && (
        <div className="mt-6">
          <h2 className="text-xl font-bold text-purple-300 mb-3">
            AI Generated Titles
          </h2>

          <div className="flex flex-col gap-3">
            {aiTitles.map((t, index) => (
              <div
                key={index}
                onClick={() => setSelectedTitle(t)}
                className={`p-3 rounded-lg cursor-pointer border
                ${selectedTitle === t ? "border-purple-500 bg-gray-700" : "border-gray-700 bg-gray-800"}`}
              >
                {t}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* CUSTOM TITLE INPUT */}
      <div className="mt-8">
        <label className="block text-purple-300 mb-2 font-semibold">
          Enter Title you Liked 
        </label>
        <input
          className="w-full p-3 rounded-lg bg-gray-900 border border-gray-700 text-white"
          value={selectedTitle}
          onChange={(e) => setSelectedTitle(e.target.value)}
          placeholder="Write your book title..."
        />
      </div>

      {/* Final Submit Button */}
      <button
        className="w-full mt-6 bg-purple-600 hover:bg-purple-700 py-3 rounded-lg font-semibold"
        onClick={handleCreateBook}
        disabled={creatingBook}
      >
        {creatingBook ? (
         <p>loading.....</p>
        ) : (
          "Create My Book"
        )}
      </button>

      {creatingBook ? (
          <div className="mt-6">
                <p className="text-center text-purple-300 mb-2">
                  Generating scenes…✨ wait for 5 to 10 minutes.
                </p>
                <div className="w-full h-2 bg-gray-700 rounded-full overflow-hidden">
                  <div className="h-full bg-gradient-to-r from-purple-500 via-pink-500 to-purple-500 animate-[scroll_1.5s_linear_infinite]"></div>
                </div>
              </div>
        ) : null}

    </div>
    </div>
  );
};

export default TitleSelection;
